.TH cliaspora 1 "2013" "version 0.1" "cliaspora"
.SH NAME
.B cliaspora
\(em A command-line client for DIASPORA*
.SH SYNOPSIS
.nf
\fBcliaspora\fP [\fIoptions\fP] \fBcommand\fP \fIargs ...\fP
\fBcliaspora\fP \fBsession\fP \fIhandle\fP [\fIpassword\fP]
\fBcliaspora\fP \fBlist\fP \fBcontacts\fP
\fBcliaspora\fP \fBlist\fP \fBmessages\fP
\fBcliaspora\fP \fBlist\fP \fBaspects\fP
\fBcliaspora\fP \fBstatus\fP
\fBcliaspora\fP \fBlookup\fP \fIname\fP|\fIhandle\fP
\fBcliaspora\fP \fBshow\fP \fBstream\fP
\fBcliaspora\fP \fBshow\fP \fBactivity\fP
\fBcliaspora\fP [\fB-e\fP] \fBpost\fP \fIaspect\fP
\fBcliaspora\fP [\fB-e\fP] \fBcomment\fP \fIpost-ID\fP
\fBcliaspora\fP [\fB-e\fP] \fBmessage\fP \fIhandle\fP [\fIsubject\fP]
\fBcliaspora\fP [\fB-e\fP] \fBreply\fP \fImessage-ID\fP
\fBcliaspora\fP \fBlike\fP \fIpost-ID\fP
\fBcliaspora\fP \fBfollow\fP \fBtag\fP \fItagname\fP
\fBcliaspora\fP \fBfollow\fP \fBuser\fP \fIhandle\fP \fIaspect\fP
\fBcliaspora\fP \fBadd\fP \fBaspect\fP \fIaspect-name\fP \fIpublic\fP|\fIprivate\fP
.fi
.SH DESCRIPTION
Before you can spam DIASPORA*, you have to create a session with
.IP
cliaspora session yourusername@yourpod.tld
.SH OPTIONS
.TP
.B -e
Use the editor defined by the environment variable EDITOR to compose
your message, reply, post, or comment.
.SH COMMANDS
.TP
.B session
Creates a new session.
.TP
.B status
Shows the number of new notifications and new messages.
.TP
.B show
Shows the first few posts of your main \fBstream\fP or your \fBactivity\fP
stream. The output is in troff format and intended to be piped into
\'preconv | groff -Tutf8\'.
.TP
.B lookup
Looks up the \fIhandle\fP or \fIname\fP on DIASPORA*.
.TP
.B list
Lists your \fBcontact\fPs, the index of your private \fBmessage\fPs, or your
\fBaspect\fPs.
.TP
.B post
Sends a new post to the given \fIaspect\fP. If \fIaspect\fP is 'public', the
post will be visible to everybody.
.TP
.B comment
Sends a comment to the given \fIpost-ID\fP.
.TP
.B message
Sends a private message to the given \fIhandle\fP.
.TP
.B reply
Sends a reply to the given private \fImessage-ID\fP.
.TP
.B like
\'Likes\' the post with the given \fIpost-ID\fP.
.TP
.B follow user
Adds the user with the given \fIhandle\fP to the \fIaspect\fP.
.TP
.B follow tag
Adds \fItag-name\fP to your tag list.
.TP
.B add aspect
Adds \fIaspect-name\fP to your aspect list.
.SH FILES
.nf
$HOME/.cliasporarc
$HOME/.cliaspora.postponed
.fi
.SH AUTHOR
.PD 0
Marcel Kaiser <mk@nic-nac-project.org>

